build: use `uv` and `ruff`
xarray-contrib/xeofs pull request #160
Opened 2024-03-31 19:16 UTC by slevang

So this would be replacing `poetry` with yet another new shiny tool, but I would argue the benefits are worth it. `uv` is a drop-in replacement for `pip`, and `ruff` is their linter/formatter tool. Both are incredibly fast (written in rust), have a lot of convenient options, and are seeing rapid adoption across the python ecosystem.

One really nice feature of `uv` is the `--resolution` arg which I've used here to run tests on a "minimal" version, using lowest supported python version of 3.10 and lowest specified versions of all our primary dependencies. Then the 3.11 and 3.12 jobs run with `--resolution=highest` which will always have us testing against new versions.

The substantive changes of this PR are the `pyproject.toml` and the GH Actions. Everything else is only the result of running ruff's linter (almost all of them auto-fixed). Mostly unused imports, trimming whitespace, and a few other random things like truthy/falsy checks and unused f-strings.

Only thing I haven't tested here is the `build_command` and uploading of wheels to pypi, but it should work fine.

2024-04-02 08:48 UTC, nicrie commented
Hey @slevang that's awesome ! I heard about these things recently coming out from Astral and would love to give it a try and see how they work. Expecting my first child literally today :)  - so I won't have time to review anytime soon. I'm OK giving it a try 👍

2024-04-02 12:57 UTC, slevang commented
Amazing, congrats! Hope all goes smoothly, and enjoy those early days :smiling_face_with_three_hearts:

2024-04-11 22:38 UTC, nicrie commented on docs/environment.yml
> -    - xeofs
Nice! This is so much cleaner! =)

2024-04-11 22:38 UTC, nicrie commented on docs/environment.yml
> +    - -e ../.[docs]
Nice! This is so much cleaner!

2024-04-11 22:41 UTC, nicrie approved these changes
That's great - looking forward to see it in action! Thank you @slevang !

2024-04-11 23:48 UTC, nicrie requested changes
One additional thought: we probably want to update the contributing guide, specifically the section about [how to create a local env](https://github.com/xarray-contrib/xeofs/blob/main/docs/overview_3_contributing.rst#2-set-up-your-development-environment). Instead of poetry, would you prefer `pip install -e .` and `pip install -e .[docs]` or rather `uv`?

2024-04-12 21:17 UTC, slevang commented
Good point. I went with basic `pip` to keep things simple. I also had to add those two system dependencies to the conda env creation to get the docs dependencies to install properly.

2024-04-13 21:46 UTC, nicrie approved these changes

2024-04-13 21:47 UTC, merged